# Generated by Django 2.2.7 on 2019-11-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventgen', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update',
            new_name='updated',
        ),
    ]
