# Generated by Django 2.2.7 on 2019-11-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_birthday',
            new_name='date_of_birth',
        ),
    ]
