# Generated by Django 2.2.7 on 2019-11-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191119_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('secret', "Don't say")], default='secret', max_length=10),
        ),
    ]
